/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as UnauthenticatedSignUpIndexImport } from './routes/_unauthenticated/sign-up/index'
import { Route as UnauthenticatedLoginIndexImport } from './routes/_unauthenticated/login/index'
import { Route as AuthenticatedStudyKitCreateIndexImport } from './routes/_authenticated/study-kit/create/index'
import { Route as AuthenticatedStudyKitIdIndexImport } from './routes/_authenticated/study-kit/$id/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnauthenticatedSignUpIndexRoute = UnauthenticatedSignUpIndexImport.update(
  {
    id: '/_unauthenticated/sign-up/',
    path: '/sign-up/',
    getParentRoute: () => rootRoute,
  } as any,
)

const UnauthenticatedLoginIndexRoute = UnauthenticatedLoginIndexImport.update({
  id: '/_unauthenticated/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedStudyKitCreateIndexRoute =
  AuthenticatedStudyKitCreateIndexImport.update({
    id: '/study-kit/create/',
    path: '/study-kit/create/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedStudyKitIdIndexRoute =
  AuthenticatedStudyKitIdIndexImport.update({
    id: '/study-kit/$id/',
    path: '/study-kit/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/login/': {
      id: '/_unauthenticated/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/sign-up/': {
      id: '/_unauthenticated/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthenticatedSignUpIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/study-kit/$id/': {
      id: '/_authenticated/study-kit/$id/'
      path: '/study-kit/$id'
      fullPath: '/study-kit/$id'
      preLoaderRoute: typeof AuthenticatedStudyKitIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/study-kit/create/': {
      id: '/_authenticated/study-kit/create/'
      path: '/study-kit/create'
      fullPath: '/study-kit/create'
      preLoaderRoute: typeof AuthenticatedStudyKitCreateIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedStudyKitIdIndexRoute: typeof AuthenticatedStudyKitIdIndexRoute
  AuthenticatedStudyKitCreateIndexRoute: typeof AuthenticatedStudyKitCreateIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedStudyKitIdIndexRoute: AuthenticatedStudyKitIdIndexRoute,
  AuthenticatedStudyKitCreateIndexRoute: AuthenticatedStudyKitCreateIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof UnauthenticatedLoginIndexRoute
  '/sign-up': typeof UnauthenticatedSignUpIndexRoute
  '/study-kit/$id': typeof AuthenticatedStudyKitIdIndexRoute
  '/study-kit/create': typeof AuthenticatedStudyKitCreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof UnauthenticatedLoginIndexRoute
  '/sign-up': typeof UnauthenticatedSignUpIndexRoute
  '/study-kit/$id': typeof AuthenticatedStudyKitIdIndexRoute
  '/study-kit/create': typeof AuthenticatedStudyKitCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_unauthenticated/login/': typeof UnauthenticatedLoginIndexRoute
  '/_unauthenticated/sign-up/': typeof UnauthenticatedSignUpIndexRoute
  '/_authenticated/study-kit/$id/': typeof AuthenticatedStudyKitIdIndexRoute
  '/_authenticated/study-kit/create/': typeof AuthenticatedStudyKitCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/sign-up'
    | '/study-kit/$id'
    | '/study-kit/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/sign-up'
    | '/study-kit/$id'
    | '/study-kit/create'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_unauthenticated/login/'
    | '/_unauthenticated/sign-up/'
    | '/_authenticated/study-kit/$id/'
    | '/_authenticated/study-kit/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  UnauthenticatedLoginIndexRoute: typeof UnauthenticatedLoginIndexRoute
  UnauthenticatedSignUpIndexRoute: typeof UnauthenticatedSignUpIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  UnauthenticatedLoginIndexRoute: UnauthenticatedLoginIndexRoute,
  UnauthenticatedSignUpIndexRoute: UnauthenticatedSignUpIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about",
        "/_unauthenticated/login/",
        "/_unauthenticated/sign-up/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/study-kit/$id/",
        "/_authenticated/study-kit/create/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_unauthenticated/login/": {
      "filePath": "_unauthenticated/login/index.tsx"
    },
    "/_unauthenticated/sign-up/": {
      "filePath": "_unauthenticated/sign-up/index.tsx"
    },
    "/_authenticated/study-kit/$id/": {
      "filePath": "_authenticated/study-kit/$id/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/study-kit/create/": {
      "filePath": "_authenticated/study-kit/create/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
